name: Main

on: [push, pull_request]

jobs:
  lint:
    name: Lints Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        run: |
          rustup component add rustfmt clippy

      - name: Check Formatting
        run: |
          cargo fmt --all -- --check

      - name: Fetch before build
        run: cargo fetch

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -Dwarnings

  test:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Run Tests
        run: |
          cargo test
